/*
 * System call switch table.
 *
 * DO NOT EDIT-- To regenerate this file, edit syscalls.master followed
 *               by running make sysent in the same directory.
 */

#include "opt_compat.h"

#ifdef __i386__
#include "opt_compatdf12.h"
#endif

#include <sys/param.h>
#include <sys/sysent.h>
#include <sys/sysproto.h>
#include <sys/statvfs.h>
#include <emulation/43bsd/stat.h>
#include <emulation/dragonfly12/stat.h>

#define AS(name) ((sizeof(struct name) - sizeof(struct sysmsg)) / sizeof(register_t))

#ifdef COMPAT_43
#define compat(n, name) n, (sy_call_t *)__CONCAT(sys_,__CONCAT(o,name))
#else
#define compat(n, name) 0, (sy_call_t *)sys_nosys
#endif

#ifdef COMPAT_DF12
#define compatdf12(n, name) n, (sy_call_t *)__CONCAT(sys_,__CONCAT(dfbsd12_,name))
#else
#define compatdf12(n, name) 0, (sy_call_t *)sys_nosys
#endif

/* The casts are bogus but will do for now. */
struct sysent sysent[] = {
#ifdef COMPAT_43
#endif
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 0 = syscall */
	{ AS(exit_args), (sy_call_t *)sys_exit , 0 },	/* 1 = exit */
	{ 0, (sy_call_t *)sys_fork , SYF_CAPENABLED },	/* 2 = fork */
	{ AS(read_args), (sy_call_t *)sys_read , SYF_CAPENABLED },	/* 3 = read */
	{ AS(write_args), (sy_call_t *)sys_write , SYF_CAPENABLED },	/* 4 = write */
	{ AS(open_args), (sy_call_t *)sys_open , SYF_CAPENABLED },	/* 5 = open */
	{ AS(close_args), (sy_call_t *)sys_close , SYF_CAPENABLED },	/* 6 = close */
	{ AS(wait_args), (sy_call_t *)sys_wait4 , 0 },	/* 7 = wait4 */
	{ compat(AS(ocreat_args),creat) , 0 },		/* 8 = old creat */
	{ AS(link_args), (sy_call_t *)sys_link , 0 },	/* 9 = link */
	{ AS(unlink_args), (sy_call_t *)sys_unlink , 0 },	/* 10 = unlink */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 11 = obsolete execv */
	{ AS(chdir_args), (sy_call_t *)sys_chdir , 0 },	/* 12 = chdir */
	{ AS(fchdir_args), (sy_call_t *)sys_fchdir , 0 },	/* 13 = fchdir */
	{ AS(mknod_args), (sy_call_t *)sys_mknod , 0 },	/* 14 = mknod */
	{ AS(chmod_args), (sy_call_t *)sys_chmod , 0 },	/* 15 = chmod */
	{ AS(chown_args), (sy_call_t *)sys_chown , 0 },	/* 16 = chown */
	{ AS(obreak_args), (sy_call_t *)sys_obreak , SYF_CAPENABLED },	/* 17 = break */
	{ AS(getfsstat_args), (sy_call_t *)sys_getfsstat , 0 },	/* 18 = getfsstat */
	{ compat(AS(olseek_args),lseek) , SYF_CAPENABLED },	/* 19 = old lseek */
	{ 0, (sy_call_t *)sys_getpid , SYF_CAPENABLED },	/* 20 = getpid */
	{ AS(mount_args), (sy_call_t *)sys_mount , 0 },	/* 21 = mount */
	{ AS(unmount_args), (sy_call_t *)sys_unmount , 0 },	/* 22 = unmount */
	{ AS(setuid_args), (sy_call_t *)sys_setuid , SYF_CAPENABLED },	/* 23 = setuid */
	{ 0, (sy_call_t *)sys_getuid , SYF_CAPENABLED },	/* 24 = getuid */
	{ 0, (sy_call_t *)sys_geteuid , SYF_CAPENABLED },	/* 25 = geteuid */
	{ AS(ptrace_args), (sy_call_t *)sys_ptrace , 0 },	/* 26 = ptrace */
	{ AS(recvmsg_args), (sy_call_t *)sys_recvmsg , SYF_CAPENABLED },	/* 27 = recvmsg */
	{ AS(sendmsg_args), (sy_call_t *)sys_sendmsg , SYF_CAPENABLED },	/* 28 = sendmsg */
	{ AS(recvfrom_args), (sy_call_t *)sys_recvfrom , SYF_CAPENABLED },	/* 29 = recvfrom */
	{ AS(accept_args), (sy_call_t *)sys_accept , SYF_CAPENABLED },	/* 30 = accept */
	{ AS(getpeername_args), (sy_call_t *)sys_getpeername , SYF_CAPENABLED },	/* 31 = getpeername */
	{ AS(getsockname_args), (sy_call_t *)sys_getsockname , SYF_CAPENABLED },	/* 32 = getsockname */
	{ AS(access_args), (sy_call_t *)sys_access , 0 },	/* 33 = access */
	{ AS(chflags_args), (sy_call_t *)sys_chflags , 0 },	/* 34 = chflags */
	{ AS(fchflags_args), (sy_call_t *)sys_fchflags , SYF_CAPENABLED },	/* 35 = fchflags */
	{ 0, (sy_call_t *)sys_sync , SYF_CAPENABLED },	/* 36 = sync */
	{ AS(kill_args), (sy_call_t *)sys_kill , SYF_CAPENABLED },	/* 37 = kill */
	{ compat(AS(ostat_args),stat) , 0 },		/* 38 = old stat */
	{ 0, (sy_call_t *)sys_getppid , SYF_CAPENABLED },	/* 39 = getppid */
	{ compat(AS(olstat_args),lstat) , 0 },		/* 40 = old lstat */
	{ AS(dup_args), (sy_call_t *)sys_dup , SYF_CAPENABLED },	/* 41 = dup */
	{ 0, (sy_call_t *)sys_pipe , SYF_CAPENABLED },	/* 42 = pipe */
	{ 0, (sy_call_t *)sys_getegid , SYF_CAPENABLED },	/* 43 = getegid */
	{ AS(profil_args), (sy_call_t *)sys_profil , SYF_CAPENABLED },	/* 44 = profil */
	{ AS(ktrace_args), (sy_call_t *)sys_ktrace , 0 },	/* 45 = ktrace */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 46 = obsolete freebsd3_sigaction */
	{ 0, (sy_call_t *)sys_getgid , SYF_CAPENABLED },	/* 47 = getgid */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 48 = obsolete freebsd3_sigprocmask */
	{ AS(getlogin_args), (sy_call_t *)sys_getlogin , SYF_CAPENABLED },	/* 49 = getlogin */
	{ AS(setlogin_args), (sy_call_t *)sys_setlogin , 0 },	/* 50 = setlogin */
	{ AS(acct_args), (sy_call_t *)sys_acct , 0 },	/* 51 = acct */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 52 = obsolete freebsd3_sigpending */
	{ AS(sigaltstack_args), (sy_call_t *)sys_sigaltstack , SYF_CAPENABLED },	/* 53 = sigaltstack */
	{ AS(ioctl_args), (sy_call_t *)sys_ioctl , SYF_CAPENABLED },	/* 54 = ioctl */
	{ AS(reboot_args), (sy_call_t *)sys_reboot , 0 },	/* 55 = reboot */
	{ AS(revoke_args), (sy_call_t *)sys_revoke , 0 },	/* 56 = revoke */
	{ AS(symlink_args), (sy_call_t *)sys_symlink , 0 },	/* 57 = symlink */
	{ AS(readlink_args), (sy_call_t *)sys_readlink , 0 },	/* 58 = readlink */
	{ AS(execve_args), (sy_call_t *)sys_execve , 0 },	/* 59 = execve */
	{ AS(umask_args), (sy_call_t *)sys_umask , SYF_CAPENABLED },	/* 60 = umask */
	{ AS(chroot_args), (sy_call_t *)sys_chroot , 0 },	/* 61 = chroot */
	{ compat(AS(ofstat_args),fstat) , SYF_CAPENABLED },	/* 62 = old fstat */
	{ compat(AS(getkerninfo_args),getkerninfo) , 0 },	/* 63 = old getkerninfo */
	{ compat(0,getpagesize) , SYF_CAPENABLED },	/* 64 = old getpagesize */
	{ AS(msync_args), (sy_call_t *)sys_msync , SYF_CAPENABLED },	/* 65 = msync */
	{ 0, (sy_call_t *)sys_vfork , 0 },		/* 66 = vfork */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 67 = obsolete vread */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 68 = obsolete vwrite */
	{ AS(sbrk_args), (sy_call_t *)sys_sbrk , SYF_CAPENABLED },	/* 69 = sbrk */
	{ AS(sstk_args), (sy_call_t *)sys_sstk , SYF_CAPENABLED },	/* 70 = sstk */
	{ compat(AS(ommap_args),mmap) , SYF_CAPENABLED },	/* 71 = old mmap */
	{ compat(AS(ovadvise_args),vadvise) , 0 },	/* 72 = old vadvise */
	{ AS(munmap_args), (sy_call_t *)sys_munmap , SYF_CAPENABLED },	/* 73 = munmap */
	{ AS(mprotect_args), (sy_call_t *)sys_mprotect , SYF_CAPENABLED },	/* 74 = mprotect */
	{ AS(madvise_args), (sy_call_t *)sys_madvise , SYF_CAPENABLED },	/* 75 = madvise */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 76 = obsolete vhangup */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 77 = obsolete vlimit */
	{ AS(mincore_args), (sy_call_t *)sys_mincore , SYF_CAPENABLED },	/* 78 = mincore */
	{ AS(getgroups_args), (sy_call_t *)sys_getgroups , SYF_CAPENABLED },	/* 79 = getgroups */
	{ AS(setgroups_args), (sy_call_t *)sys_setgroups , 0 },	/* 80 = setgroups */
	{ 0, (sy_call_t *)sys_getpgrp , SYF_CAPENABLED },	/* 81 = getpgrp */
	{ AS(setpgid_args), (sy_call_t *)sys_setpgid , 0 },	/* 82 = setpgid */
	{ AS(setitimer_args), (sy_call_t *)sys_setitimer , SYF_CAPENABLED },	/* 83 = setitimer */
	{ compat(0,wait) , 0 },				/* 84 = old wait */
	{ AS(swapon_args), (sy_call_t *)sys_swapon , 0 },	/* 85 = swapon */
	{ AS(getitimer_args), (sy_call_t *)sys_getitimer , SYF_CAPENABLED },	/* 86 = getitimer */
	{ compat(AS(gethostname_args),gethostname) , SYF_CAPENABLED },	/* 87 = old gethostname */
	{ compat(AS(sethostname_args),sethostname) , 0 },	/* 88 = old sethostname */
	{ 0, (sy_call_t *)sys_getdtablesize , 0 },	/* 89 = getdtablesize */
	{ AS(dup2_args), (sy_call_t *)sys_dup2 , SYF_CAPENABLED },	/* 90 = dup2 */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 91 = getdopt */
	{ AS(fcntl_args), (sy_call_t *)sys_fcntl , SYF_CAPENABLED },	/* 92 = fcntl */
	{ AS(select_args), (sy_call_t *)sys_select , SYF_CAPENABLED },	/* 93 = select */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 94 = setdopt */
	{ AS(fsync_args), (sy_call_t *)sys_fsync , SYF_CAPENABLED },	/* 95 = fsync */
	{ AS(setpriority_args), (sy_call_t *)sys_setpriority , SYF_CAPENABLED },	/* 96 = setpriority */
	{ AS(socket_args), (sy_call_t *)sys_socket , SYF_CAPENABLED },	/* 97 = socket */
	{ AS(connect_args), (sy_call_t *)sys_connect , 0 },	/* 98 = connect */
	{ compat(AS(accept_args),accept) , SYF_CAPENABLED },	/* 99 = old accept */
	{ AS(getpriority_args), (sy_call_t *)sys_getpriority , SYF_CAPENABLED },	/* 100 = getpriority */
	{ compat(AS(osend_args),send) , SYF_CAPENABLED },	/* 101 = old send */
	{ compat(AS(orecv_args),recv) , SYF_CAPENABLED },	/* 102 = old recv */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 103 = obsolete freebsd3_sigreturn */
	{ AS(bind_args), (sy_call_t *)sys_bind , 0 },	/* 104 = bind */
	{ AS(setsockopt_args), (sy_call_t *)sys_setsockopt , SYF_CAPENABLED },	/* 105 = setsockopt */
	{ AS(listen_args), (sy_call_t *)sys_listen , SYF_CAPENABLED },	/* 106 = listen */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 107 = obsolete vtimes */
	{ compat(AS(osigvec_args),sigvec) , SYF_CAPENABLED },	/* 108 = old sigvec */
	{ compat(AS(osigblock_args),sigblock) , SYF_CAPENABLED },	/* 109 = old sigblock */
	{ compat(AS(osigsetmask_args),sigsetmask) , SYF_CAPENABLED },	/* 110 = old sigsetmask */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 111 = obsolete freebsd3_sigsuspend */
	{ compat(AS(osigstack_args),sigstack) , SYF_CAPENABLED },	/* 112 = old sigstack */
	{ compat(AS(orecvmsg_args),recvmsg) , SYF_CAPENABLED },	/* 113 = old recvmsg */
	{ compat(AS(osendmsg_args),sendmsg) , SYF_CAPENABLED },	/* 114 = old sendmsg */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 115 = obsolete vtrace */
	{ AS(gettimeofday_args), (sy_call_t *)sys_gettimeofday , SYF_CAPENABLED },	/* 116 = gettimeofday */
	{ AS(getrusage_args), (sy_call_t *)sys_getrusage , SYF_CAPENABLED },	/* 117 = getrusage */
	{ AS(getsockopt_args), (sy_call_t *)sys_getsockopt , SYF_CAPENABLED },	/* 118 = getsockopt */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 119 = resuba */
	{ AS(readv_args), (sy_call_t *)sys_readv , SYF_CAPENABLED },	/* 120 = readv */
	{ AS(writev_args), (sy_call_t *)sys_writev , SYF_CAPENABLED },	/* 121 = writev */
	{ AS(settimeofday_args), (sy_call_t *)sys_settimeofday , 0 },	/* 122 = settimeofday */
	{ AS(fchown_args), (sy_call_t *)sys_fchown , SYF_CAPENABLED },	/* 123 = fchown */
	{ AS(fchmod_args), (sy_call_t *)sys_fchmod , SYF_CAPENABLED },	/* 124 = fchmod */
	{ compat(AS(recvfrom_args),recvfrom) , SYF_CAPENABLED },	/* 125 = old recvfrom */
	{ AS(setreuid_args), (sy_call_t *)sys_setreuid , SYF_CAPENABLED },	/* 126 = setreuid */
	{ AS(setregid_args), (sy_call_t *)sys_setregid , SYF_CAPENABLED },	/* 127 = setregid */
	{ AS(rename_args), (sy_call_t *)sys_rename , 0 },	/* 128 = rename */
	{ compat(AS(otruncate_args),truncate) , 0 },	/* 129 = old truncate */
	{ compat(AS(oftruncate_args),ftruncate) , SYF_CAPENABLED },	/* 130 = old ftruncate */
	{ AS(flock_args), (sy_call_t *)sys_flock , SYF_CAPENABLED },	/* 131 = flock */
	{ AS(mkfifo_args), (sy_call_t *)sys_mkfifo , 0 },	/* 132 = mkfifo */
	{ AS(sendto_args), (sy_call_t *)sys_sendto , SYF_CAPENABLED },	/* 133 = sendto */
	{ AS(shutdown_args), (sy_call_t *)sys_shutdown , SYF_CAPENABLED },	/* 134 = shutdown */
	{ AS(socketpair_args), (sy_call_t *)sys_socketpair , SYF_CAPENABLED },	/* 135 = socketpair */
	{ AS(mkdir_args), (sy_call_t *)sys_mkdir , 0 },	/* 136 = mkdir */
	{ AS(rmdir_args), (sy_call_t *)sys_rmdir , 0 },	/* 137 = rmdir */
	{ AS(utimes_args), (sy_call_t *)sys_utimes , 0 },	/* 138 = utimes */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 139 = obsolete 4.2 sigreturn */
	{ AS(adjtime_args), (sy_call_t *)sys_adjtime , 0 },	/* 140 = adjtime */
	{ compat(AS(ogetpeername_args),getpeername) , SYF_CAPENABLED },	/* 141 = old getpeername */
	{ compat(0,gethostid) , SYF_CAPENABLED },	/* 142 = old gethostid */
	{ compat(AS(osethostid_args),sethostid) , 0 },	/* 143 = old sethostid */
	{ compat(AS(ogetrlimit_args),getrlimit) , SYF_CAPENABLED },	/* 144 = old getrlimit */
	{ compat(AS(osetrlimit_args),setrlimit) , SYF_CAPENABLED },	/* 145 = old setrlimit */
	{ compat(AS(okillpg_args),killpg) , 0 },	/* 146 = old killpg */
	{ 0, (sy_call_t *)sys_setsid , SYF_CAPENABLED },	/* 147 = setsid */
	{ AS(quotactl_args), (sy_call_t *)sys_quotactl , 0 },	/* 148 = quotactl */
	{ compat(0,quota) , 0 },			/* 149 = old quota */
	{ compat(AS(getsockname_args),getsockname) , SYF_CAPENABLED },	/* 150 = old getsockname */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 151 = sem_lock */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 152 = sem_wakeup */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 153 = asyncdaemon */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 154 = nosys */
	{ AS(nfssvc_args), (sy_call_t *)sys_nosys , 0 },	/* 155 = nfssvc */
	{ compat(AS(ogetdirentries_args),getdirentries) , SYF_CAPENABLED },	/* 156 = old getdirentries */
	{ AS(statfs_args), (sy_call_t *)sys_statfs , 0 },	/* 157 = statfs */
	{ AS(fstatfs_args), (sy_call_t *)sys_fstatfs , SYF_CAPENABLED },	/* 158 = fstatfs */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 159 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 160 = nosys */
	{ AS(getfh_args), (sy_call_t *)sys_getfh , 0 },	/* 161 = getfh */
	{ AS(getdomainname_args), (sy_call_t *)sys_getdomainname , SYF_CAPENABLED },	/* 162 = getdomainname */
	{ AS(setdomainname_args), (sy_call_t *)sys_setdomainname , 0 },	/* 163 = setdomainname */
	{ AS(uname_args), (sy_call_t *)sys_uname , 0 },	/* 164 = uname */
	{ AS(sysarch_args), (sy_call_t *)sys_sysarch , SYF_CAPENABLED },	/* 165 = sysarch */
	{ AS(rtprio_args), (sy_call_t *)sys_rtprio , SYF_CAPENABLED },	/* 166 = rtprio */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 167 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 168 = nosys */
	{ AS(semsys_args), (sy_call_t *)sys_semsys , 0 },	/* 169 = semsys */
	{ AS(msgsys_args), (sy_call_t *)sys_msgsys , 0 },	/* 170 = msgsys */
	{ AS(shmsys_args), (sy_call_t *)sys_shmsys , 0 },	/* 171 = shmsys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 172 = nosys */
	{ AS(extpread_args), (sy_call_t *)sys_extpread , 0 },	/* 173 = extpread */
	{ AS(extpwrite_args), (sy_call_t *)sys_extpwrite , 0 },	/* 174 = extpwrite */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 175 = nosys */
	{ AS(ntp_adjtime_args), (sy_call_t *)sys_ntp_adjtime , 0 },	/* 176 = ntp_adjtime */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 177 = sfork */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 178 = getdescriptor */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 179 = setdescriptor */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 180 = nosys */
	{ AS(setgid_args), (sy_call_t *)sys_setgid , SYF_CAPENABLED },	/* 181 = setgid */
	{ AS(setegid_args), (sy_call_t *)sys_setegid , SYF_CAPENABLED },	/* 182 = setegid */
	{ AS(seteuid_args), (sy_call_t *)sys_seteuid , SYF_CAPENABLED },	/* 183 = seteuid */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 184 = lfs_bmapv */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 185 = lfs_markv */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 186 = lfs_segclean */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 187 = lfs_segwait */
	{ compatdf12(AS(dfbsd12_stat_args),stat) , 0 },	/* 188 = old stat */
	{ compatdf12(AS(dfbsd12_fstat_args),fstat) , SYF_CAPENABLED },	/* 189 = old fstat */
	{ compatdf12(AS(dfbsd12_lstat_args),lstat) , 0 },	/* 190 = old lstat */
	{ AS(pathconf_args), (sy_call_t *)sys_pathconf , 0 },	/* 191 = pathconf */
	{ AS(fpathconf_args), (sy_call_t *)sys_fpathconf , SYF_CAPENABLED },	/* 192 = fpathconf */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 193 = nosys */
	{ AS(__getrlimit_args), (sy_call_t *)sys_getrlimit , SYF_CAPENABLED },	/* 194 = getrlimit */
	{ AS(__setrlimit_args), (sy_call_t *)sys_setrlimit , SYF_CAPENABLED },	/* 195 = setrlimit */
	{ compatdf12(AS(dfbsd12_getdirentries_args),getdirentries) , SYF_CAPENABLED },	/* 196 = old getdirentries */
	{ AS(mmap_args), (sy_call_t *)sys_mmap , SYF_CAPENABLED },	/* 197 = mmap */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 198 = __syscall */
	{ AS(lseek_args), (sy_call_t *)sys_lseek , SYF_CAPENABLED },	/* 199 = lseek */
	{ AS(truncate_args), (sy_call_t *)sys_truncate , 0 },	/* 200 = truncate */
	{ AS(ftruncate_args), (sy_call_t *)sys_ftruncate , SYF_CAPENABLED },	/* 201 = ftruncate */
	{ AS(sysctl_args), (sy_call_t *)sys___sysctl , SYF_CAPENABLED },	/* 202 = __sysctl */
	{ AS(mlock_args), (sy_call_t *)sys_mlock , SYF_CAPENABLED },	/* 203 = mlock */
	{ AS(munlock_args), (sy_call_t *)sys_munlock , SYF_CAPENABLED },	/* 204 = munlock */
	{ AS(undelete_args), (sy_call_t *)sys_undelete , 0 },	/* 205 = undelete */
	{ AS(futimes_args), (sy_call_t *)sys_futimes , SYF_CAPENABLED },	/* 206 = futimes */
	{ AS(getpgid_args), (sy_call_t *)sys_getpgid , SYF_CAPENABLED },	/* 207 = getpgid */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 208 = newreboot */
	{ AS(poll_args), (sy_call_t *)sys_poll , SYF_CAPENABLED },	/* 209 = poll */
	{ AS(nosys_args), (sy_call_t *)sys_lkmnosys , 0 },	/* 210 = lkmnosys */
	{ AS(nosys_args), (sy_call_t *)sys_lkmnosys , 0 },	/* 211 = lkmnosys */
	{ AS(nosys_args), (sy_call_t *)sys_lkmnosys , 0 },	/* 212 = lkmnosys */
	{ AS(nosys_args), (sy_call_t *)sys_lkmnosys , 0 },	/* 213 = lkmnosys */
	{ AS(nosys_args), (sy_call_t *)sys_lkmnosys , 0 },	/* 214 = lkmnosys */
	{ AS(nosys_args), (sy_call_t *)sys_lkmnosys , 0 },	/* 215 = lkmnosys */
	{ AS(nosys_args), (sy_call_t *)sys_lkmnosys , 0 },	/* 216 = lkmnosys */
	{ AS(nosys_args), (sy_call_t *)sys_lkmnosys , 0 },	/* 217 = lkmnosys */
	{ AS(nosys_args), (sy_call_t *)sys_lkmnosys , 0 },	/* 218 = lkmnosys */
	{ AS(nosys_args), (sy_call_t *)sys_lkmnosys , 0 },	/* 219 = lkmnosys */
	{ AS(__semctl_args), (sy_call_t *)sys___semctl , 0 },	/* 220 = __semctl */
	{ AS(semget_args), (sy_call_t *)sys_semget , 0 },	/* 221 = semget */
	{ AS(semop_args), (sy_call_t *)sys_semop , 0 },	/* 222 = semop */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 223 = semconfig */
	{ AS(msgctl_args), (sy_call_t *)sys_msgctl , 0 },	/* 224 = msgctl */
	{ AS(msgget_args), (sy_call_t *)sys_msgget , 0 },	/* 225 = msgget */
	{ AS(msgsnd_args), (sy_call_t *)sys_msgsnd , 0 },	/* 226 = msgsnd */
	{ AS(msgrcv_args), (sy_call_t *)sys_msgrcv , 0 },	/* 227 = msgrcv */
	{ AS(shmat_args), (sy_call_t *)sys_shmat , 0 },	/* 228 = shmat */
	{ AS(shmctl_args), (sy_call_t *)sys_shmctl , 0 },	/* 229 = shmctl */
	{ AS(shmdt_args), (sy_call_t *)sys_shmdt , 0 },	/* 230 = shmdt */
	{ AS(shmget_args), (sy_call_t *)sys_shmget , 0 },	/* 231 = shmget */
	{ AS(clock_gettime_args), (sy_call_t *)sys_clock_gettime , SYF_CAPENABLED },	/* 232 = clock_gettime */
	{ AS(clock_settime_args), (sy_call_t *)sys_clock_settime , 0 },	/* 233 = clock_settime */
	{ AS(clock_getres_args), (sy_call_t *)sys_clock_getres , SYF_CAPENABLED },	/* 234 = clock_getres */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 235 = timer_create */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 236 = timer_delete */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 237 = timer_settime */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 238 = timer_gettime */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 239 = timer_getoverrun */
	{ AS(nanosleep_args), (sy_call_t *)sys_nanosleep , SYF_CAPENABLED },	/* 240 = nanosleep */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 241 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 242 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 243 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 244 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 245 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 246 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 247 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 248 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 249 = nosys */
	{ AS(minherit_args), (sy_call_t *)sys_minherit , SYF_CAPENABLED },	/* 250 = minherit */
	{ AS(rfork_args), (sy_call_t *)sys_rfork , 0 },	/* 251 = rfork */
	{ AS(openbsd_poll_args), (sy_call_t *)sys_openbsd_poll , SYF_CAPENABLED },	/* 252 = openbsd_poll */
	{ 0, (sy_call_t *)sys_issetugid , SYF_CAPENABLED },	/* 253 = issetugid */
	{ AS(lchown_args), (sy_call_t *)sys_lchown , 0 },	/* 254 = lchown */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 255 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 256 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 257 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 258 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 259 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 260 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 261 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 262 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 263 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 264 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 265 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 266 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 267 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 268 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 269 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 270 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 271 = nosys */
	{ compatdf12(AS(dfbsd12_getdents_args),getdents) , SYF_CAPENABLED },	/* 272 = old getdents */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 273 = nosys */
	{ AS(lchmod_args), (sy_call_t *)sys_lchmod , 0 },	/* 274 = lchmod */
	{ AS(lchown_args), (sy_call_t *)sys_lchown , 0 },	/* 275 = netbsd_lchown */
	{ AS(lutimes_args), (sy_call_t *)sys_lutimes , 0 },	/* 276 = lutimes */
	{ AS(msync_args), (sy_call_t *)sys_msync , SYF_CAPENABLED },	/* 277 = netbsd_msync */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 278 = obsolete { */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 279 = obsolete { */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 280 = obsolete { */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 281 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 282 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 283 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 284 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 285 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 286 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 287 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 288 = nosys */
	{ AS(extpreadv_args), (sy_call_t *)sys_extpreadv , 0 },	/* 289 = extpreadv */
	{ AS(extpwritev_args), (sy_call_t *)sys_extpwritev , 0 },	/* 290 = extpwritev */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 291 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 292 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 293 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 294 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 295 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 296 = nosys */
	{ AS(fhstatfs_args), (sy_call_t *)sys_fhstatfs , 0 },	/* 297 = fhstatfs */
	{ AS(fhopen_args), (sy_call_t *)sys_fhopen , 0 },	/* 298 = fhopen */
	{ compatdf12(AS(dfbsd12_fhstat_args),fhstat) , 0 },	/* 299 = old fhstat */
	{ AS(modnext_args), (sy_call_t *)sys_modnext , 0 },	/* 300 = modnext */
	{ AS(modstat_args), (sy_call_t *)sys_modstat , 0 },	/* 301 = modstat */
	{ AS(modfnext_args), (sy_call_t *)sys_modfnext , 0 },	/* 302 = modfnext */
	{ AS(modfind_args), (sy_call_t *)sys_modfind , 0 },	/* 303 = modfind */
	{ AS(kldload_args), (sy_call_t *)sys_kldload , 0 },	/* 304 = kldload */
	{ AS(kldunload_args), (sy_call_t *)sys_kldunload , 0 },	/* 305 = kldunload */
	{ AS(kldfind_args), (sy_call_t *)sys_kldfind , 0 },	/* 306 = kldfind */
	{ AS(kldnext_args), (sy_call_t *)sys_kldnext , 0 },	/* 307 = kldnext */
	{ AS(kldstat_args), (sy_call_t *)sys_kldstat , 0 },	/* 308 = kldstat */
	{ AS(kldfirstmod_args), (sy_call_t *)sys_kldfirstmod , 0 },	/* 309 = kldfirstmod */
	{ AS(getsid_args), (sy_call_t *)sys_getsid , SYF_CAPENABLED },	/* 310 = getsid */
	{ AS(setresuid_args), (sy_call_t *)sys_setresuid , SYF_CAPENABLED },	/* 311 = setresuid */
	{ AS(setresgid_args), (sy_call_t *)sys_setresgid , SYF_CAPENABLED },	/* 312 = setresgid */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 313 = obsolete signanosleep */
	{ AS(aio_return_args), (sy_call_t *)sys_aio_return , SYF_CAPENABLED },	/* 314 = aio_return */
	{ AS(aio_suspend_args), (sy_call_t *)sys_aio_suspend , SYF_CAPENABLED },	/* 315 = aio_suspend */
	{ AS(aio_cancel_args), (sy_call_t *)sys_aio_cancel , SYF_CAPENABLED },	/* 316 = aio_cancel */
	{ AS(aio_error_args), (sy_call_t *)sys_aio_error , SYF_CAPENABLED },	/* 317 = aio_error */
	{ AS(aio_read_args), (sy_call_t *)sys_aio_read , SYF_CAPENABLED },	/* 318 = aio_read */
	{ AS(aio_write_args), (sy_call_t *)sys_aio_write , SYF_CAPENABLED },	/* 319 = aio_write */
	{ AS(lio_listio_args), (sy_call_t *)sys_lio_listio , SYF_CAPENABLED },	/* 320 = lio_listio */
	{ 0, (sy_call_t *)sys_yield , SYF_CAPENABLED },	/* 321 = yield */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 322 = thr_sleep */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 323 = thr_wakeup */
	{ AS(mlockall_args), (sy_call_t *)sys_mlockall , SYF_CAPENABLED },	/* 324 = mlockall */
	{ 0, (sy_call_t *)sys_munlockall , SYF_CAPENABLED },	/* 325 = munlockall */
	{ AS(__getcwd_args), (sy_call_t *)sys___getcwd , 0 },	/* 326 = __getcwd */
	{ AS(sched_setparam_args), (sy_call_t *)sys_sched_setparam , SYF_CAPENABLED },	/* 327 = sched_setparam */
	{ AS(sched_getparam_args), (sy_call_t *)sys_sched_getparam , SYF_CAPENABLED },	/* 328 = sched_getparam */
	{ AS(sched_setscheduler_args), (sy_call_t *)sys_sched_setscheduler , SYF_CAPENABLED },	/* 329 = sched_setscheduler */
	{ AS(sched_getscheduler_args), (sy_call_t *)sys_sched_getscheduler , SYF_CAPENABLED },	/* 330 = sched_getscheduler */
	{ 0, (sy_call_t *)sys_sched_yield , SYF_CAPENABLED },	/* 331 = sched_yield */
	{ AS(sched_get_priority_max_args), (sy_call_t *)sys_sched_get_priority_max , SYF_CAPENABLED },	/* 332 = sched_get_priority_max */
	{ AS(sched_get_priority_min_args), (sy_call_t *)sys_sched_get_priority_min , SYF_CAPENABLED },	/* 333 = sched_get_priority_min */
	{ AS(sched_rr_get_interval_args), (sy_call_t *)sys_sched_rr_get_interval , 0 },	/* 334 = sched_rr_get_interval */
	{ AS(utrace_args), (sy_call_t *)sys_utrace , SYF_CAPENABLED },	/* 335 = utrace */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 336 = obsolete freebsd4_sendfile */
	{ AS(kldsym_args), (sy_call_t *)sys_kldsym , 0 },	/* 337 = kldsym */
	{ AS(jail_args), (sy_call_t *)sys_jail , 0 },	/* 338 = jail */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 339 = pioctl */
	{ AS(sigprocmask_args), (sy_call_t *)sys_sigprocmask , SYF_CAPENABLED },	/* 340 = sigprocmask */
	{ AS(sigsuspend_args), (sy_call_t *)sys_sigsuspend , SYF_CAPENABLED },	/* 341 = sigsuspend */
	{ AS(sigaction_args), (sy_call_t *)sys_sigaction , SYF_CAPENABLED },	/* 342 = sigaction */
	{ AS(sigpending_args), (sy_call_t *)sys_sigpending , SYF_CAPENABLED },	/* 343 = sigpending */
	{ AS(sigreturn_args), (sy_call_t *)sys_sigreturn , SYF_CAPENABLED },	/* 344 = sigreturn */
	{ AS(sigtimedwait_args), (sy_call_t *)sys_sigtimedwait , SYF_CAPENABLED },	/* 345 = sigtimedwait */
	{ AS(sigwaitinfo_args), (sy_call_t *)sys_sigwaitinfo , SYF_CAPENABLED },	/* 346 = sigwaitinfo */
	{ AS(__acl_get_file_args), (sy_call_t *)sys___acl_get_file , 0 },	/* 347 = __acl_get_file */
	{ AS(__acl_set_file_args), (sy_call_t *)sys___acl_set_file , 0 },	/* 348 = __acl_set_file */
	{ AS(__acl_get_fd_args), (sy_call_t *)sys___acl_get_fd , SYF_CAPENABLED },	/* 349 = __acl_get_fd */
	{ AS(__acl_set_fd_args), (sy_call_t *)sys___acl_set_fd , SYF_CAPENABLED },	/* 350 = __acl_set_fd */
	{ AS(__acl_delete_file_args), (sy_call_t *)sys___acl_delete_file , 0 },	/* 351 = __acl_delete_file */
	{ AS(__acl_delete_fd_args), (sy_call_t *)sys___acl_delete_fd , SYF_CAPENABLED },	/* 352 = __acl_delete_fd */
	{ AS(__acl_aclcheck_file_args), (sy_call_t *)sys___acl_aclcheck_file , 0 },	/* 353 = __acl_aclcheck_file */
	{ AS(__acl_aclcheck_fd_args), (sy_call_t *)sys___acl_aclcheck_fd , SYF_CAPENABLED },	/* 354 = __acl_aclcheck_fd */
	{ AS(extattrctl_args), (sy_call_t *)sys_extattrctl , 0 },	/* 355 = extattrctl */
	{ AS(extattr_set_file_args), (sy_call_t *)sys_extattr_set_file , 0 },	/* 356 = extattr_set_file */
	{ AS(extattr_get_file_args), (sy_call_t *)sys_extattr_get_file , 0 },	/* 357 = extattr_get_file */
	{ AS(extattr_delete_file_args), (sy_call_t *)sys_extattr_delete_file , 0 },	/* 358 = extattr_delete_file */
	{ AS(aio_waitcomplete_args), (sy_call_t *)sys_aio_waitcomplete , SYF_CAPENABLED },	/* 359 = aio_waitcomplete */
	{ AS(getresuid_args), (sy_call_t *)sys_getresuid , SYF_CAPENABLED },	/* 360 = getresuid */
	{ AS(getresgid_args), (sy_call_t *)sys_getresgid , SYF_CAPENABLED },	/* 361 = getresgid */
	{ 0, (sy_call_t *)sys_kqueue , SYF_CAPENABLED },	/* 362 = kqueue */
	{ AS(kevent_args), (sy_call_t *)sys_kevent , SYF_CAPENABLED },	/* 363 = kevent */
	{ AS(sctp_peeloff_args), (sy_call_t *)sys_sctp_peeloff , SYF_CAPENABLED },	/* 364 = sctp_peeloff */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 365 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 366 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 367 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 368 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 369 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 370 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 371 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 372 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 373 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 374 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 375 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 376 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 377 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 378 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 379 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 380 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 381 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 382 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 383 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 384 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 385 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 386 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 387 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 388 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 389 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 390 = nosys */
	{ AS(lchflags_args), (sy_call_t *)sys_lchflags , 0 },	/* 391 = lchflags */
	{ AS(uuidgen_args), (sy_call_t *)sys_uuidgen , SYF_CAPENABLED },	/* 392 = uuidgen */
	{ AS(sendfile_args), (sy_call_t *)sys_sendfile , SYF_CAPENABLED },	/* 393 = sendfile */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 394 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 395 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 396 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 397 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 398 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 399 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 400 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 401 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 402 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 403 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 404 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 405 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 406 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 407 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 408 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 409 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 410 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 411 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 412 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 413 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 414 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 415 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 416 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 417 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 418 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 419 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 420 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 421 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 422 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 423 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 424 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 425 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 426 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 427 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 428 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 429 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 430 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 431 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 432 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 433 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 434 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 435 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 436 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 437 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 438 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 439 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 440 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 441 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 442 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 443 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 444 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 445 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 446 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 447 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 448 = nosys */
	{ 0, (sy_call_t *)sys_nosys, 0 },			/* 449 = nosys */
	{ AS(varsym_set_args), (sy_call_t *)sys_varsym_set , 0 },	/* 450 = varsym_set */
	{ AS(varsym_get_args), (sy_call_t *)sys_varsym_get , 0 },	/* 451 = varsym_get */
	{ AS(varsym_list_args), (sy_call_t *)sys_varsym_list , 0 },	/* 452 = varsym_list */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 453 = obsolete upc_register */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 454 = obsolete upc_control */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 455 = obsolete caps_sys_service */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 456 = obsolete caps_sys_client */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 457 = obsolete caps_sys_close */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 458 = obsolete caps_sys_put */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 459 = obsolete caps_sys_reply */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 460 = obsolete caps_sys_get */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 461 = obsolete caps_sys_wait */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 462 = obsolete caps_sys_abort */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 463 = obsolete caps_sys_getgen */
	{ 0, (sy_call_t *)sys_nosys , 0 },		/* 464 = obsolete caps_sys_setgen */
	{ AS(exec_sys_register_args), (sy_call_t *)sys_exec_sys_register , 0 },	/* 465 = exec_sys_register */
	{ AS(exec_sys_unregister_args), (sy_call_t *)sys_exec_sys_unregister , 0 },	/* 466 = exec_sys_unregister */
	{ AS(sys_checkpoint_args), (sy_call_t *)sys_sys_checkpoint , 0 },	/* 467 = sys_checkpoint */
	{ AS(mountctl_args), (sy_call_t *)sys_mountctl , 0 },	/* 468 = mountctl */
	{ AS(umtx_sleep_args), (sy_call_t *)sys_umtx_sleep , 0 },	/* 469 = umtx_sleep */
	{ AS(umtx_wakeup_args), (sy_call_t *)sys_umtx_wakeup , 0 },	/* 470 = umtx_wakeup */
	{ AS(jail_attach_args), (sy_call_t *)sys_jail_attach , 0 },	/* 471 = jail_attach */
	{ AS(set_tls_area_args), (sy_call_t *)sys_set_tls_area , 0 },	/* 472 = set_tls_area */
	{ AS(get_tls_area_args), (sy_call_t *)sys_get_tls_area , 0 },	/* 473 = get_tls_area */
	{ AS(closefrom_args), (sy_call_t *)sys_closefrom , SYF_CAPENABLED },	/* 474 = closefrom */
	{ AS(stat_args), (sy_call_t *)sys_stat , 0 },	/* 475 = stat */
	{ AS(fstat_args), (sy_call_t *)sys_fstat , SYF_CAPENABLED },	/* 476 = fstat */
	{ AS(lstat_args), (sy_call_t *)sys_lstat , 0 },	/* 477 = lstat */
	{ AS(fhstat_args), (sy_call_t *)sys_fhstat , 0 },	/* 478 = fhstat */
	{ AS(getdirentries_args), (sy_call_t *)sys_getdirentries , SYF_CAPENABLED },	/* 479 = getdirentries */
	{ AS(getdents_args), (sy_call_t *)sys_getdents , SYF_CAPENABLED },	/* 480 = getdents */
	{ AS(usched_set_args), (sy_call_t *)sys_usched_set , 0 },	/* 481 = usched_set */
	{ AS(extaccept_args), (sy_call_t *)sys_extaccept , 0 },	/* 482 = extaccept */
	{ AS(extconnect_args), (sy_call_t *)sys_extconnect , 0 },	/* 483 = extconnect */
	{ AS(syslink_args), (sy_call_t *)sys_syslink , 0 },	/* 484 = syslink */
	{ AS(mcontrol_args), (sy_call_t *)sys_mcontrol , 0 },	/* 485 = mcontrol */
	{ AS(vmspace_create_args), (sy_call_t *)sys_vmspace_create , 0 },	/* 486 = vmspace_create */
	{ AS(vmspace_destroy_args), (sy_call_t *)sys_vmspace_destroy , 0 },	/* 487 = vmspace_destroy */
	{ AS(vmspace_ctl_args), (sy_call_t *)sys_vmspace_ctl , 0 },	/* 488 = vmspace_ctl */
	{ AS(vmspace_mmap_args), (sy_call_t *)sys_vmspace_mmap , 0 },	/* 489 = vmspace_mmap */
	{ AS(vmspace_munmap_args), (sy_call_t *)sys_vmspace_munmap , 0 },	/* 490 = vmspace_munmap */
	{ AS(vmspace_mcontrol_args), (sy_call_t *)sys_vmspace_mcontrol , 0 },	/* 491 = vmspace_mcontrol */
	{ AS(vmspace_pread_args), (sy_call_t *)sys_vmspace_pread , 0 },	/* 492 = vmspace_pread */
	{ AS(vmspace_pwrite_args), (sy_call_t *)sys_vmspace_pwrite , 0 },	/* 493 = vmspace_pwrite */
	{ AS(extexit_args), (sy_call_t *)sys_extexit , 0 },	/* 494 = extexit */
	{ AS(lwp_create_args), (sy_call_t *)sys_lwp_create , 0 },	/* 495 = lwp_create */
	{ 0, (sy_call_t *)sys_lwp_gettid , 0 },		/* 496 = lwp_gettid */
	{ AS(lwp_kill_args), (sy_call_t *)sys_lwp_kill , 0 },	/* 497 = lwp_kill */
	{ AS(lwp_rtprio_args), (sy_call_t *)sys_lwp_rtprio , 0 },	/* 498 = lwp_rtprio */
	{ AS(pselect_args), (sy_call_t *)sys_pselect , 0 },	/* 499 = pselect */
	{ AS(statvfs_args), (sy_call_t *)sys_statvfs , 0 },	/* 500 = statvfs */
	{ AS(fstatvfs_args), (sy_call_t *)sys_fstatvfs , 0 },	/* 501 = fstatvfs */
	{ AS(fhstatvfs_args), (sy_call_t *)sys_fhstatvfs , 0 },	/* 502 = fhstatvfs */
	{ AS(getvfsstat_args), (sy_call_t *)sys_getvfsstat , 0 },	/* 503 = getvfsstat */
	{ AS(openat_args), (sy_call_t *)sys_openat , SYF_CAPENABLED },	/* 504 = openat */
	{ AS(fstatat_args), (sy_call_t *)sys_fstatat , SYF_CAPENABLED },	/* 505 = fstatat */
	{ AS(fchmodat_args), (sy_call_t *)sys_fchmodat , SYF_CAPENABLED },	/* 506 = fchmodat */
	{ AS(fchownat_args), (sy_call_t *)sys_fchownat , SYF_CAPENABLED },	/* 507 = fchownat */
	{ AS(unlinkat_args), (sy_call_t *)sys_unlinkat , SYF_CAPENABLED },	/* 508 = unlinkat */
	{ AS(faccessat_args), (sy_call_t *)sys_faccessat , SYF_CAPENABLED },	/* 509 = faccessat */
	{ AS(mq_open_args), (sy_call_t *)sys_mq_open , 0 },	/* 510 = mq_open */
	{ AS(mq_close_args), (sy_call_t *)sys_mq_close , 0 },	/* 511 = mq_close */
	{ AS(mq_unlink_args), (sy_call_t *)sys_mq_unlink , 0 },	/* 512 = mq_unlink */
	{ AS(mq_getattr_args), (sy_call_t *)sys_mq_getattr , 0 },	/* 513 = mq_getattr */
	{ AS(mq_setattr_args), (sy_call_t *)sys_mq_setattr , 0 },	/* 514 = mq_setattr */
	{ AS(mq_notify_args), (sy_call_t *)sys_mq_notify , 0 },	/* 515 = mq_notify */
	{ AS(mq_send_args), (sy_call_t *)sys_mq_send , 0 },	/* 516 = mq_send */
	{ AS(mq_receive_args), (sy_call_t *)sys_mq_receive , 0 },	/* 517 = mq_receive */
	{ AS(mq_timedsend_args), (sy_call_t *)sys_mq_timedsend , 0 },	/* 518 = mq_timedsend */
	{ AS(mq_timedreceive_args), (sy_call_t *)sys_mq_timedreceive , 0 },	/* 519 = mq_timedreceive */
	{ AS(ioprio_set_args), (sy_call_t *)sys_ioprio_set , 0 },	/* 520 = ioprio_set */
	{ AS(ioprio_get_args), (sy_call_t *)sys_ioprio_get , 0 },	/* 521 = ioprio_get */
	{ AS(chroot_kernel_args), (sy_call_t *)sys_chroot_kernel , 0 },	/* 522 = chroot_kernel */
	{ AS(renameat_args), (sy_call_t *)sys_renameat , SYF_CAPENABLED },	/* 523 = renameat */
	{ AS(mkdirat_args), (sy_call_t *)sys_mkdirat , SYF_CAPENABLED },	/* 524 = mkdirat */
	{ AS(mkfifoat_args), (sy_call_t *)sys_mkfifoat , SYF_CAPENABLED },	/* 525 = mkfifoat */
	{ AS(mknodat_args), (sy_call_t *)sys_mknodat , SYF_CAPENABLED },	/* 526 = mknodat */
	{ AS(readlinkat_args), (sy_call_t *)sys_readlinkat , SYF_CAPENABLED },	/* 527 = readlinkat */
	{ AS(symlinkat_args), (sy_call_t *)sys_symlinkat , SYF_CAPENABLED },	/* 528 = symlinkat */
	{ AS(swapoff_args), (sy_call_t *)sys_swapoff , 0 },	/* 529 = swapoff */
	{ AS(vquotactl_args), (sy_call_t *)sys_vquotactl , 0 },	/* 530 = vquotactl */
	{ AS(linkat_args), (sy_call_t *)sys_linkat , SYF_CAPENABLED },	/* 531 = linkat */
	{ AS(eaccess_args), (sy_call_t *)sys_eaccess , 0 },	/* 532 = eaccess */
	{ AS(lpathconf_args), (sy_call_t *)sys_lpathconf , 0 },	/* 533 = lpathconf */
	{ AS(cap_getmode_args), (sy_call_t *)sys_cap_getmode , SYF_CAPENABLED },	/* 534 = cap_getmode */
	{ 0, (sy_call_t *)sys_cap_enter , SYF_CAPENABLED },	/* 535 = cap_enter */
	{ AS(cap_rights_get_args), (sy_call_t *)sys_cap_rights_get , SYF_CAPENABLED },	/* 536 = cap_rights_get */
	{ AS(cap_rights_limit_args), (sy_call_t *)sys_cap_rights_limit , SYF_CAPENABLED },	/* 537 = cap_rights_limit */
	{ AS(cap_ioctls_limit_args), (sy_call_t *)sys_cap_ioctls_limit , SYF_CAPENABLED },	/* 538 = cap_ioctls_limit */
	{ AS(cap_ioctls_get_args), (sy_call_t *)sys_cap_ioctls_get , SYF_CAPENABLED },	/* 539 = cap_ioctls_get */
	{ AS(cap_fcntls_limit_args), (sy_call_t *)sys_cap_fcntls_limit , SYF_CAPENABLED },	/* 540 = cap_fcntls_limit */
	{ AS(cap_fcntls_get_args), (sy_call_t *)sys_cap_fcntls_get , SYF_CAPENABLED },	/* 541 = cap_fcntls_get */
	{ AS(connectat_args), (sy_call_t *)sys_connectat , SYF_CAPENABLED },	/* 542 = connectat */
	{ AS(bindat_args), (sy_call_t *)sys_bindat , SYF_CAPENABLED },	/* 543 = bindat */
};
